spring:
  profiles:
    active: rdbms, dev
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_app}
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  security:
    user:
      name: user
      password: password

logging:
  level:
    com.hxs: DEBUG

server:
  port: 8080

info:
  version: 0.0.1